#cloud-config

hostname: raspberry-0
# update /etc/hosts according to hostname (otherwise sudo will complain)
manage_etc_hosts: true
locale: en_US.UTF-8
timezone: Europe/Berlin

users:
- default # pi user
- name: tim
  gecos: Tim Ebert
  groups: sudo
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  # set to false to allow password login for this user
  # only for verifying with dockerpi, passwd auth over SSH should be disabled
  lock_passwd: false
  shell: /bin/bash
  # salt + hashed password, generate with `mkpasswd` or `openssl passwd -6`
  passwd: $6$U3.pM4pSkWuWC/AV$c/GZctLhbySMEKPF2wIgMrQB4jM7lPToi4oFlI9b53XSvcT/C8KM.HYnsQdXJI9ICmqXbVOwIhzovXk8JAbMc1
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDzEE4Z7wZXrO6HZF5XjSeF0qIBLLbaJiI5w3TDnzh6k+Mcg17ahBYLyA+CFkZOpU668hh3AbY+ess2iVkPQ9JvurnKEVUO7Q2kyU8YaXbX+eSsaaw7Y9eNb140br9K8/4DwE2q4cXlSTkhsHu9XJJads6ByXhVo2RZIsY07BWGdAAwv4nThVTMehxjzstCMWnfSEa1oHgd59R09hAqHHqJ1Al8RfgKzFevRv+zFj2bftZRH6bjLlRIj2izkIPjdgrwME9/2tJ5CwBelxnVa9KPtd0ndu0E3GfBwEmw0De3bGD1rTST3l29klBTJL0HXZrFMBKPcoE/CiBk8ZINOdjxutmr6FegLdsrIEQqyjC9KNaG8wPKXGGqfmtXX4dpqxf7z5W730D3BeNlT51a/NHFw+uTBOe+CmwKKRmBvUS/CHEUIo5di4bs342ZaTUrRdoIKz1kde3TSIcC7Q0T3X0GIFGaHcxqWWIz9PxFm1YKQ/WvIQXdVtk/rui82wWyGCrBRfsMivwmVkS05C6E1lsyKAFK6w2jX1P49ZuzP/gfd6oF7u0K/17MEmF/Lqg2ea5KwtN3djUhnR9njxR1iy0UNDPYzoOwqbNi8ENO9CO8If6rgJdTCwH3u2no5fL2bJwyuVQF2kser4DDDgCBIzegB4BpY7gs9yNEJqcS4bUTqQ==
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJsGtuJYWgCwGHznLg8A2Iqm124z4vvoZmC0cIwr1D6V

# set to true to allow ssh password authentication (disabled by default)
ssh_pwauth: false

bootcmd:
# disable ipv6 on all interfaces
- sysctl net.ipv6.conf.all.disable_ipv6=1
